# Generated by Django 5.1.3 on 2024-11-28 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id_diretoria', models.AutoField(primary_key=True, serialize=False)),
                ('name_diretoria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'diretoria',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('name_area', models.CharField(max_length=45)),
                ('id_diretoria', models.ForeignKey(db_column='id_diretoria', on_delete=django.db.models.deletion.DO_NOTHING, to='back_log.diretoria')),
            ],
            options={
                'db_table': 'area',
                'unique_together': {('id_area', 'id_diretoria')},
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id_gestor', models.AutoField(db_column='id_gestor', primary_key=True, serialize=False)),
                ('name_gestor', models.CharField(max_length=45)),
                ('email_gest', models.EmailField(max_length=45)),
                ('identificador', models.CharField(blank=True, max_length=4, null=True)),
                ('id_diretoria', models.ForeignKey(db_column='id_diretoria', on_delete=django.db.models.deletion.DO_NOTHING, to='back_log.diretoria')),
            ],
            options={
                'db_table': 'gestor',
                'unique_together': {('id_gestor', 'id_diretoria')},
            },
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id_subarea', models.AutoField(primary_key=True, serialize=False)),
                ('name_subarea', models.CharField(max_length=45)),
                ('id_area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.DO_NOTHING, to='back_log.area')),
                ('id_diretoria', models.ForeignKey(db_column='id_diretoria', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subarea_id_diretoria_set', to='back_log.diretoria')),
            ],
            options={
                'db_table': 'subarea',
                'unique_together': {('id_subarea', 'id_area', 'id_diretoria')},
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('name_colaborador', models.CharField(max_length=45)),
                ('id_area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.DO_NOTHING, related_name='colaborador_id_area_set', to='back_log.area')),
                ('id_diretoria', models.ForeignKey(db_column='id_diretoria', on_delete=django.db.models.deletion.DO_NOTHING, related_name='colaborador_id_diretoria_set', to='back_log.diretoria')),
                ('id_gestor', models.ForeignKey(db_column='id_gestor', on_delete=django.db.models.deletion.DO_NOTHING, to='back_log.gestor')),
                ('id_subarea', models.ForeignKey(db_column='id_subarea', on_delete=django.db.models.deletion.DO_NOTHING, to='back_log.subarea')),
            ],
            options={
                'db_table': 'colaborador',
                'unique_together': {('id_colaborador', 'id_gestor', 'id_subarea', 'id_area', 'id_diretoria')},
            },
        ),
    ]
