# Generated by Django 5.1.3 on 2024-12-04 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
