# Generated by Django 5.1.3 on 2024-12-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0002_gestor_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name_area',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='diretoria',
            name='name_diretoria',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name_subarea',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.CreateModel(
            name='PA',
            fields=[
                ('id_pa', models.AutoField(primary_key=True, serialize=False)),
                ('mnemonico', models.CharField(max_length=255, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('id_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_log.area')),
                ('id_diretoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_log.diretoria')),
                ('id_gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_log.gestor')),
                ('id_subarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_log.subarea')),
            ],
        ),
    ]
