# Generated by Django 5.1.3 on 2024-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0003_alter_area_name_area_alter_diretoria_name_diretoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarea',
            name='name_subarea',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
