# Generated by Django 5.1.3 on 2024-12-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0004_alter_subarea_name_subarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='id_subarea',
            field=models.ForeignKey(db_column='id_subarea', null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_log.subarea'),
        ),
    ]
