# Generated by Django 5.1.3 on 2024-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0006_alter_colaborador_id_subarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarea',
            name='name_subarea',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
