# Generated by Django 5.1.3 on 2024-12-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0007_alter_subarea_name_subarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='siglaar',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='diretoria',
            name='sigladir',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
