# Generated by Django 5.1.3 on 2024-12-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0008_area_siglaar_diretoria_sigladir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('duracao_horas', models.PositiveIntegerField()),
                ('pas', models.ManyToManyField(related_name='cursos', to='back_log.pa')),
            ],
        ),
    ]
