# Generated by Django 5.1.3 on 2024-12-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0009_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_publicado',
            field=models.DateTimeField(null=True),
        ),
    ]
