# Generated by Django 5.1.3 on 2024-12-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0010_curso_data_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='siglaar',
            field=models.CharField(default='N/A', max_length=22),
        ),
        migrations.AlterField(
            model_name='diretoria',
            name='sigladir',
            field=models.CharField(default='N/A', max_length=22),
        ),
    ]
