# Generated by Django 5.1.3 on 2024-12-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0011_alter_area_siglaar_alter_diretoria_sigladir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='siglaar',
            field=models.CharField(default='N/A', max_length=40),
        ),
    ]
