# Generated by Django 5.1.3 on 2024-12-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0013_alter_area_siglaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pa',
            name='id_colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_log.colaborador'),
        ),
    ]
