# Generated by Django 5.1.3 on 2025-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0014_pa_id_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
