# Generated by Django 5.1.3 on 2025-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0015_gestor_changed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateTimeField(null=True),
        ),
    ]
