# Generated by Django 5.1.3 on 2025-02-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0016_colaborador_data_admissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pa',
            name='id_colaborador',
        ),
        migrations.AlterUniqueTogether(
            name='subarea',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subarea',
            name='id_area',
        ),
        migrations.RemoveField(
            model_name='subarea',
            name='id_diretoria',
        ),
        migrations.RemoveField(
            model_name='pa',
            name='id_subarea',
        ),
        migrations.RemoveField(
            model_name='area',
            name='siglaar',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_publicado',
        ),
        migrations.RemoveField(
            model_name='pa',
            name='id_area',
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.DeleteModel(
            name='Subarea',
        ),
    ]
