# Generated by Django 5.1.3 on 2025-03-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0017_remove_pa_id_colaborador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='id_area',
            field=models.ForeignKey(blank=True, db_column='id_area', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='back_log.area'),
        ),
    ]
