# Generated by Django 5.1.3 on 2025-03-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0018_gestor_id_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('id_diretoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='back_log.diretoria')),
                ('id_gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='back_log.gestor')),
            ],
        ),
    ]
