# Generated by Django 5.1.3 on 2025-03-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0020_colaborador_id_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='id_diretoria',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='pas',
        ),
        migrations.RemoveField(
            model_name='pa',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='pa',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pa',
            name='id_diretoria',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='id_pa',
            field=models.ForeignKey(db_column='id_pa', null=True, on_delete=django.db.models.deletion.CASCADE, to='back_log.pa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_pa',
            field=models.ForeignKey(db_column='id_pa', null=True, on_delete=django.db.models.deletion.CASCADE, to='back_log.pa'),
        ),
    ]
