# Generated by Django 5.1.3 on 2025-03-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0021_remove_colaborador_id_diretoria_remove_curso_pas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='id_area',
        ),
        migrations.AlterModelTable(
            name='pa',
            table='back_log_pa',
        ),
    ]
