# Generated by Django 5.1.3 on 2025-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0022_remove_colaborador_id_area_alter_pa_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pa',
            name='nome',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pa',
            name='mnemonico',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
