# Generated by Django 5.1.3 on 2025-04-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0023_pa_nome_alter_pa_mnemonico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diretoria',
            name='sigladir',
        ),
    ]
