# Generated by Django 5.1.3 on 2025-04-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0024_remove_diretoria_sigladir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name_area',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
