# Generated by Django 5.1.3 on 2025-04-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0025_alter_area_name_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='id_area',
        ),
        migrations.AddField(
            model_name='area',
            name='gestor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_log.gestor'),
        ),
    ]
