# Generated by Django 5.1.3 on 2025-04-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0026_remove_gestor_id_area_area_gestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='id_gestor',
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id_subarea', models.AutoField(primary_key=True, serialize=False)),
                ('name_subarea', models.CharField(max_length=80)),
                ('id_area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.CASCADE, to='back_log.area')),
                ('id_diretoria', models.ForeignKey(db_column='id_diretoria', on_delete=django.db.models.deletion.DO_NOTHING, to='back_log.diretoria')),
                ('id_gestor', models.ForeignKey(db_column='id_gestor', on_delete=django.db.models.deletion.CASCADE, to='back_log.gestor')),
            ],
            options={
                'db_table': 'subarea',
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='id_subarea',
            field=models.ForeignKey(blank=True, db_column='id_subarea', null=True, on_delete=django.db.models.deletion.CASCADE, to='back_log.subarea'),
        ),
    ]
