# Generated by Django 5.1.3 on 2025-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0027_remove_area_gestor_remove_colaborador_id_gestor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='changed_password',
            field=models.BooleanField(default=True),
        ),
    ]
