# Generated by Django 5.1.3 on 2025-04-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0029_alter_gestor_changed_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='changed_password',
        ),
    ]
