# Generated by Django 5.1.3 on 2025-04-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0031_gestor_changed_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='id_subarea',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='id_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_log.gestor'),
        ),
        migrations.DeleteModel(
            name='Subarea',
        ),
    ]
