# Generated by Django 5.1.3 on 2025-04-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0032_remove_colaborador_id_subarea_colaborador_id_gestor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='changed_password',
        ),
    ]
