# Generated by Django 5.1.3 on 2025-04-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0033_remove_gestor_changed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
