# Generated by Django 5.1.3 on 2025-04-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0034_gestor_changed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pa',
            name='mnemonico',
            field=models.CharField(blank=True, max_length=405),
        ),
        migrations.AlterField(
            model_name='pa',
            name='nome',
            field=models.CharField(blank=True, max_length=405, unique=True),
        ),
    ]
