# Generated by Django 5.1.3 on 2025-04-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0035_alter_pa_mnemonico_alter_pa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pa',
            name='nome',
            field=models.CharField(blank=True, max_length=405),
        ),
    ]
