# Generated by Django 5.1.3 on 2025-04-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0036_alter_pa_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='id_gestor',
        ),
    ]
