# Generated by Django 5.1.3 on 2025-04-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0037_remove_colaborador_id_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=275),
        ),
    ]
