# Generated by Django 5.1.3 on 2025-04-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_log', '0038_alter_colaborador_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='id_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_log.gestor'),
        ),
    ]
